add batch method
elvenworks/kafka-conector pull request #6
Opened 2021-09-08 00:59 UTC by pedroribeiro

2021-09-08 11:45 UTC, LeandroFranciscato requested changes

2021-09-08 11:45 UTC, LeandroFranciscato commented on kafka.go
> +func (k *Kafka) BatchConsumeWithFallback(topic []string, groupName string, maxBufferSize, numberOfRoutines int) (msgChannel chan []byte, err error) {
Apenas por questões de nomenclatura, eu renomearia o prâmetro para `topics` e a variável nova para `topicsWithFallback`

2021-09-10 16:36 UTC, pedroribeiro commented on kafka.go
> +func (k *Kafka) BatchConsumeWithFallback(topic []string, groupName string, maxBufferSize, numberOfRoutines int) (msgChannel chan []byte, err error) {
Feito

2021-09-10 16:48 UTC, LeandroFranciscato approved these changes

2021-09-10 16:48 UTC, merged

2021-09-10 16:49 UTC, LeandroFranciscato commented
Mergeado para master e nova tag gerada `v1.2.8`